# Generated by Django 5.1 on 2024-08-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('fuel_type', models.CharField(choices=[('бензин', 'бензин'), ('дизель', 'дизель'), ('гибрид', 'гибрид'), ('электричество', 'электричество')], max_length=100, verbose_name='Тип топлива')),
                ('transmission_type', models.CharField(choices=[('механическая', 'механическая'), ('автоматическая', 'автоматическая'), ('робот', 'робот'), ('вариатор', 'вариатор')], max_length=100, verbose_name='Тип коробки передач')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
